config/routes.rb
# encoding: utf-8
Xmadweb::Application.routes.draw do


  # 考生的试卷
  # 作者： ryan
  # 添加时间: 2013-4-17
  # 修改添加看自己的试卷
  # 2013-4-18
  resources :vocabulary_exams do 
    # 试卷
    collection do
        post "save_voc"
    end
    get "my", :on => :collection
  end

  # 单词和意思
  # 作者： ryan
  # 添加时间: 2013-4-16
  resources :vocabularies  do 
    resources :vocabulary_meanings
  end
  # 显示个人的考试列表
  # 作者： ryan
  # 添加时间: 2013-4-18
  resources :word_child_categories do
    get "me", :on => :collection
  end

  # 单词类别
  # 作者： ryan
  # 添加时间: 2013-4-15
  # 修改时间： 2013-4-16
  # 添加三个方法
  resources :word_categories do 
    get 'list', :on => :collection
    resources :word_child_categories do 
      member do
        get 'upload_word'
        # 显示词表
        get "show_word"
      end

      collection do
        post 'save_upload'
        get "list"
        post "save_voc"
      end
    end
  end

  # 统计谷歌广告
  resources :google_analytics do
    get 'show_traffic', :on => :collection
    get 'user_index', :on => :collection
  end

  # 关联广告页面
  resources :web_pages do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end
  # 关联类类别
  resources :tag_categories  do
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  # 关联位置
  resources :positions  do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end

  # 关联活动
  resources :campaigns do 
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  #批量上传词汇
  get "upload_xml/index"
  post "upload_xml/upload_file"

  # 单词
  resources :words do
    # 每个单词有很多意思
    resources :meanings
    # 删除所有单词属性
    get 'delete_all', :on => :collection
  end

  # 试卷
  resources :papers do
    # 试卷里面的单词
    resources :paper_words
  end

  resources :exam_types

  resources :word_properties

  # 教学问题
  resources :teaching_problems do
    get 'closed', :on => :collection
  end
  # 教学问题的标签
  match 'teaching_problems/tags/:name' , :to => 'teaching_problems#search_by_tag_name', 
    :via => [:get], :as => "teaching_problems_by_tagname"

  # 教材
  resources :teaching_materials do
    # 所有的标签
    get 'alltags', :on => :collection
    # 用来级联选择的
    get 'tagselect', :on => :collection
    # 课程
    resources :lessons
  end
  # 教材的标签
  match 'teaching_materials/tags/:name' , :to => 'teaching_materials#search_by_tag_name', 
    :via => [:get], :as => "teaching_materials_by_tagname"

  namespace :admin do
      root :to => "base#index"
      resources :users do
        post 'activity', :on => :member
      end
  end
  # 学生功能管理
  resources :students do
    # 附加属性
    resources :ext_attributes
    # 成绩管理
    resources :results
    collection do
      get 'view'
      get 'my'
      get 'result_delay'
      get 'exam'
      get 'search_index'
    end   
    # 学生时间表追踪管理
    resources :student_timelines
    # 学生分配督导和客户经理
    resources :student_distributes
    # 学习计划
    resources :dairy_plans do
      # calendar的计划用到的json数据格式
      get 'get_plan_json', :on => :collection
      get 'get_plan_json_for_exam', :on => :collection
      get 'get_plan_json_for_mockexam', :on => :collection
      get 'get_result_json', :on => :collection
      # 课程内容
      resources :course_contents do 
        # 获取课程安排的event给fullcalendar使用
        get 'get_course_content_json', :on => :collection
      end
    end
    # student attend the exams
    resources :exams do
        get 'student', :on => :collection
        get 'todo_exam', :on => :collection
        get 'doing_exam', :on => :collection
        get 'done_exam', :on => :collection
        get 'corrected_exam', :on => :collection
        get 'never_done_exam', :on => :collection
    end
    #students have many result_papers
    resources :result_papers do
        resources :result_words
        get 'student', :on => :collection
    end
  end
  # 督导的学生
  match 'students/jpms/:id(.:format)', :to => 'students#jpms', :via => [:get], :as => "students_by_jpm"
  # 客户经理的学生
  match 'students/spms/:id(.:format)', :to => 'students#spms', :via => [:get], :as => "students_by_spm"
  # 学生成绩按日汇总查询
  match "students/results_by_day", :to => "results#all_by_day", :via => [:post], :as => "results_all_by_day"
  # 学生考情按日查询
  match "students/timelines_by_day", :to => "student_timelines#all_by_day", :via => [:post], :as => "student_timelines_all_by_day"

  
  root :to => "home#index"
  
  devise_for :users

  resources :clicks do
    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_position', :on => :collection
    post 'save_position', :on => :collection

    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_page', :on => :collection
    post 'save_page', :on => :collection

    get 'add_category', :on => :collection
    post 'save_category', :on => :collection

    get 'add_up_category', :on => :collection
    post 'save_up_category', :on => :collection


    get 'sum_campaign', :on => :collection
    get 'sum_position', :on => :collection
    get 'sum_page', :on => :collection
    get 'sum_category', :on => :collection
    get 'sum_child_category', :on => :collection
    get 'search_result', :on => :collection

    get 'core_customer', :on => :collection
    get 'referral_traffic', :on => :collection
    get 'organic_traffic', :on => :collection
    get 'index_campaign', :on => :collection
  end


  resources :advertisements
  
  match "adclick", :to => "adclick#index", :via => [:get]


end

app/models/result.rb
# encoding: utf-8
class Result < ActiveRecord::Base
  belongs_to :jpm, :class_name => "User",
      :foreign_key => "jpm_id"
  belongs_to :student, :class_name => "User",
      :foreign_key => "student_id"
  # 异常
  def exception
    case exception_type
    when 0
      "没有延迟"
    when 1
      "老师没提交"
    when 2
      "学生未完成"
    when 3 
      "学其他异常"
    when 4
      "测试改期"
    when 5
      "其他"
    end
  end
  
  def has_exception_str
    case has_exception
    when 0
      "没有"
    when 1
      "有"
    end
  end
  
  # 补交完毕了吗
  def exception_handle_str
    case exception_handle
      when true
        "完毕"
      when false
        "没有"
    end
    
  end
end

app/controllers/results_controller.rb
# encoding: utf-8
class ResultsController < ApplicationController 
  before_filter :authorize_not_student!
  before_filter :authorize_activity!
  before_filter :find_student, :except => [:all_by_day]
  # GET /results
  # GET /results.json
  def index
    @results = Result.where(:student_id => @student.id)
      .order('result_date desc')
      .paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])
    date1 = params[:result][:result_date].to_datetime.change(:hour => 1)
    @result.result_date = date1
    @result.student = @student
    @result.jpm = current_user
    respond_to do |format|
      if @result.save
        format.html { redirect_to student_results_path(@student), notice: 'Result was successfully created.' }
        format.json { render json: student_results_path(@student), status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])
    @result.student = @student
    @result.jpm = current_user
    date1 = params[:result][:result_date].to_datetime.change(:hour => 1)
    params[:result][:result_date] = date1
    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to student_results_path(@student), notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to student_results_path(@student) }
      format.json { head :no_content }
    end
  end
  # 查询成绩 按日期
  def all_by_day
    #date_org = params[:result_date].to_datetime
    date_org = DateTime.strptime(params[:result_date] + " CCT", "%Y-%m-%d %Z")
    date1 = date_org.change(:hour => 0, :min => 0, :sec => 0)
    date2 = date_org.change(:hour => 23, :min => 59, :sec => 59)
    @results = Result.joins('LEFT OUTER JOIN users ON users.id = student_id')
      .where(:result_date => date1.to_time..date2.to_time, 'users.is_activity' => true)
  end
  
  private

  def find_student
    @student = User.find(params[:student_id])
  end
end

app/views/results/all_by_day.html.erb
<h1>所有学生的成绩 按日查询</h1>
<div class="common_table">
<table border="1" cellspacing="5" cellpadding="5">
	<tr>
		<th>日期</th>
		<th>姓名</th>
		<th>督导</th>
		<th>单词A</th>
		<th>单词B</th>
		<th>听力A</th>
		<th>写作A</th>
		<th>阅读A</th>
		<th>口语A</th>
		<th>听力B</th>
		<th>写作B</th>
		<th>阅读B</th>
		<th>口语B</th>
		<th>延时</th>
		<th>原因</th>
		<th>操作</th>
	</tr>
	<%  
		total_words_score1 = 0
		total_words_num1 = 0
		total_words_score2 = 0
		total_words_num2 = 0
	%>
<% @results.each do |result| %>
	<tr>
		<td><% if result.result_date %><%= result.result_date.strftime('%Y-%m-%d') %><% end %></td>
		<td><%= link_to result.student.name, student_path(result.student) %></td>
		<td><%= result.student.jpm ? result.student.jpm.name : "未分配" %></td>
		<td><%= result.words_score1 %></td>
		<td><%= result.words_score2 %></td>
		<td><%= result.listen_words_score1 %></td>
		<td><%= result.write_words_score1 %></td>
		<td><%= result.read_words_score1 %></td>
		<td><%= result.spoken_words_score1 %></td>
		<td><%= result.listen_score1 %></td>
		<td><%= result.write_score1 %></td>
		<td><%= result.read_score1 %></td>
		<td><%= result.spoken_score1 %></td>
		<td><%= result.has_exception ? result.has_exception_str : "" %></td>
		<td><%= result.exception_type ? result.exception : "" %></td>
		<td>
			<%= link_to '查看', student_result_path(result.student,result) %> |
			<%= link_to '编辑', edit_student_result_path(result.student,result) %>
		</td>
	</tr>
	<% 
		if result.words_score1 
			total_words_score1 += result.words_score1
			total_words_num1 += 1
 		end
		if result.words_score2 
			total_words_score2 += result.words_score2
			total_words_num2 += 1
 		end 
	%>
<% end %>
</table>
</div>
<h6>单词A的平均成绩<%= (total_words_num1 != 0) ? (total_words_score1/total_words_num1).to_i : 0%></h6>
<h6>单词B的平均成绩<%= (total_words_num2 != 0) ? (total_words_score2/total_words_num2).to_i : 0%></h6>

app/views/results/edit.html.erb
<h1>编辑<%= link_to @student.name, student_path(@student) %>的成绩</h1>

	<script>
		$(function() {
			$( "#datepicker" ).datepicker();
			$( "#datepicker" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
			<% if @result.result_date %>
			$( "#datepicker" ).datepicker("setDate",'<%= @result.result_date.strftime('%Y-%m-%d') %>');
			
			<% end %>
			
		});
	</script>
<%= form_for([@student,@result], :url => student_result_path(@student,@result)) do |f| %>

  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	
    </div>
  <% end %>
	<p>
	<%= f.label :words_score1	, '单词课前测' %>
	<%= f.text_field :words_score1	 %>
	</p>
	<p>
	<%= f.label :words_score2	, '单词课后测' %>
	<%= f.text_field :words_score2	 %>
	</p>
	<p>
	<%= f.label :listen_words_score1	, '听力单词测' %>
	<%= f.text_field :listen_words_score1	 %>
	</p>
	<p>
	<%= f.label :write_words_score1	, '写作单词测' %>
	<%= f.text_field :write_words_score1	 %>
	</p>
	<p>
	<%= f.label :read_words_score1	, '阅读单词测' %>
	<%= f.text_field :read_words_score1	 %>
	</p>
	<p>
	<%= f.label :spoken_words_score1	, '口语单词测' %>
	<%= f.text_field :spoken_words_score1	 %>
	</p>
	<p>
	<%= f.label :listen_score1	, '听力课后测' %>
	<%= f.text_field :listen_score1	 %>
	</p>
	<p>
	<%= f.label :write_score1	, '写作课后测' %>
	<%= f.text_field :write_score1	 %>
	</p>
	<p>
	<%= f.label :read_score1	, '阅读课后测' %>
	<%= f.text_field :read_score1	 %>
	</p>
	<p>
	<%= f.label :spoken_score1	, '口语课后测' %>
	<%= f.text_field :spoken_score1	 %>
	</p>
	
	<p>
	<%= f.label :has_exception, "是否有延迟测试" %>
	<%= f.select(:has_exception, options_for_select({"没有" => "0","有" => "1"}, @result.has_exception ? @result.has_exception : 0) ) %>
	</p>
	
	<p>
	<%= f.label :exception_type, "成绩延迟原因" %>
	<%= f.select(:exception_type, options_for_select({"没有延迟" => "0", "老师未发邮件" => "1","学生未完成" => "2","学生异常" => "3", "测试时间为第二天或者推迟" => "4", "其他" => "5"},  @result.exception_type ?  @result.exception_type : 0) ) %>
	</p>
	
	<p>
		<%= f.label :remark	, '未出成绩说明(请填写科目,任课老师等等信息,如果学生异动,请补充说明)' %>
		<br/>
		<%= f.text_area  :remark, :cols => 100, :rows => 10 %>	
	</p>
	
	<p>
		<%= f.check_box  :exception_handle%>
		<%= f.label :exception_handle	, '补交完毕,或不再处理,直接关闭' %>			
	</p>
	
	<p>日期: <input type="text" id="datepicker" name="result[result_date]" ></p>

  <div class="actions">
    <%= f.submit '保存' %>
  </div>
<% end %>

<%= link_to '显示', student_result_path(@student,@result) %> |
<%= link_to '返回所有成绩', student_results_path(@student) %>

app/views/results/index.html.erb
<h1>所有<%= link_to @student.name, student_path(@student) %>的每日成绩</h1>

<table>
  <tr>
    <th>上课时间</th>
    <th>督导</th>
	<th>单词A</th>
	<th>单词B</th>
	<th>听力A</th>
	<th>写作A</th>
	<th>阅读A</th>
	<th>口语A</th>
	<th>听力B</th>
	<th>写作B</th>
	<th>阅读B</th>
	<th>口语B</th>
	<th>延时</th>
	<th>原因</th>
    <th>操作</th>
  </tr>
<%  
	total_words_score1 = 0
	total_words_num1 = 0
	total_words_score2 = 0
	total_words_num2 = 0
%>
<% @results.each do |result| %>
  <tr>
	<td><% if result.result_date %><%= result.result_date.strftime('%Y-%m-%d') %><% end %></td>
	<td><%= result.student.jpm ? result.student.jpm.name : "未分配" %></td>
	<td><%= result.words_score1 %></td>
	<td><%= result.words_score2 %></td>
	<td><%= result.listen_words_score1 %></td>
	<td><%= result.write_words_score1 %></td>
	<td><%= result.read_words_score1 %></td>
	<td><%= result.spoken_words_score1 %></td>
	<td><%= result.listen_score1 %></td>
	<td><%= result.write_score1 %></td>
	<td><%= result.read_score1 %></td>
	<td><%= result.spoken_score1 %></td>
	<td><%= result.has_exception ? result.has_exception_str : "" %></td>
	<td><%= result.exception_type ? result.exception : "" %></td>
    <td><%= link_to '查看', student_result_path(@student,result) %> |
    	<%= link_to '编辑', edit_student_result_path(@student,result) %> |
    	<%= link_to '删除', student_result_path(@student,result), confirm: 'Are you sure?', method: :delete %>
  </tr>
	<% 
		if result.words_score1 
			total_words_score1 += result.words_score1
			total_words_num1 += 1
 		end
		if result.words_score2 
			total_words_score2 += result.words_score2
			total_words_num2 += 1
 		end 
	%>
<% end %>
</table>
<%=h will_paginate @result, :previous_label => '上一页',  :next_label => '下一页'%>
<br />
<h6>单词A的平均成绩<%= (total_words_num1 != 0) ? (total_words_score1/total_words_num1).to_i : 0%></h6>
<h6>单词B的平均成绩<%= (total_words_num2 != 0) ? (total_words_score2/total_words_num2).to_i : 0%></h6>
<%= link_to '创建学生成绩', new_student_result_path %>

app/views/results/new.html.erb
<h1>创建每日成绩-<%= link_to @student.name, student_path(@student) %></h1>

	<script>
		$(function() {
			$( "#datepicker" ).datepicker();
			$( "#datepicker" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
		});
	</script>
<%= form_for([@student,@result], :url => student_results_path(@student)) do |f| %>

  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	
    </div>
  <% end %>
	<p>
	<%= f.label :words_score1	, '单词课前测' %>
	<%= f.text_field :words_score1	 %>
	</p>
	<p>
	<%= f.label :words_score2	, '单词课后测' %>
	<%= f.text_field :words_score2	 %>
	</p>
	<p>
	<%= f.label :listen_words_score1	, '听力单词测' %>
	<%= f.text_field :listen_words_score1	 %>
	</p>
	<p>
	<%= f.label :write_words_score1	, '写作单词测' %>
	<%= f.text_field :write_words_score1	 %>
	</p>
	<p>
	<%= f.label :read_words_score1	, '阅读单词测' %>
	<%= f.text_field :read_words_score1	 %>
	</p>
	<p>
	<%= f.label :spoken_words_score1	, '口语单词测' %>
	<%= f.text_field :spoken_words_score1	 %>
	</p>
	<p>
	<%= f.label :listen_score1	, '听力课后测' %>
	<%= f.text_field :listen_score1	 %>
	</p>
	<p>
	<%= f.label :write_score1	, '写作课后测' %>
	<%= f.text_field :write_score1	 %>
	</p>
	<p>
	<%= f.label :read_score1	, '阅读课后测' %>
	<%= f.text_field :read_score1	 %>
	</p>
	<p>
	<%= f.label :spoken_score1	, '口语课后测' %>
	<%= f.text_field :spoken_score1	 %>
	</p>
	
	<p>
	<%= f.label :has_exception, "是否有延迟测试" %>
	<%= f.select(:has_exception, options_for_select({"没有" => "0","有" => "1"}, "0") ) %>
	</p>
	
	<p>
	<%= f.label :exception_type, "成绩延迟原因" %>
	<%= f.select(:exception_type, options_for_select({"没有延迟" => "0", "老师未发邮件" => "1","学生未完成" => "2","学生异常" => "3", "测试时间为第二天或者推迟" => "4", "其他" => "5"}, "0") ) %>
	</p>
	
	<p>
		<%= f.label :remark	, '未出成绩说明(请填写科目,任课老师等等信息,如果学生异动,请补充说明)' %>
		<br/>
		<%= f.text_area  :remark, :cols => 100, :rows => 10 %>	
	</p>
	
	<p>日期: <input type="text" id="datepicker" name="result[result_date]"></p>

  <div class="actions">
    <%= f.submit '保存' %>
  </div>
<% end %>

<%= link_to '返回学生所有测试成绩', student_results_path(@student) %>

app/views/results/show.html.erb
<p>
	<div>学生姓名:<%= link_to @student.name, student_path(@student) %></div>
</p>
<p>
	<div>提交数据者:<%= @result.jpm.name %></div>
</p>
<p>
	<div>督导:<%= @result.student.jpm ? @result.student.jpm.name : "未分配" %></div>
</p>
<p>
	<div>测试成绩日期:<% if @result.result_date %><%= @result.result_date.strftime('%Y-%m-%d') %><% end %></div>
</p>
<p>
	<div>单词课前测:<%= @result.words_score1 %></div>
</p>
<p>
	<div>单词课后测:<%= @result.words_score2 %></div>
</p>
<p>
	<div>听力单词测:<%= @result.listen_words_score1 %></div>
</p>
<p>
	<div>写作单词测:<%= @result.write_words_score1 %></div>
</p>
<p>
	<div>阅读单词测:<%= @result.read_words_score1 %></div>
</p>
<p>
	<div>口语单词测:<%= @result.spoken_words_score1 %></div>
</p>
<p>
	<div>听力课后测:<%= @result.listen_score1 %></div>
</p>
<p>
	<div>写作课后测:<%= @result.write_score1 %></div>
</p>
<p>
	<div>阅读课后测:<%= @result.read_score1 %></div>
</p>
<p>
	<div>口语课后测:<%= @result.spoken_score1 %></div>
</p>
<p>
	<div>是否有成绩延时提交:<%= (@result.has_exception == 1) ? "有" : "没有" %></div>
</p>
<p>
	<div>延时提交原因:<%= @result.exception %></div>
</p>

<p>
	<div>情况详细:<br/><%= @result.remark %></div>
</p>

<p>
	<div>补交完毕:<%= @result.exception_handle_str %></div>
</p>

<%= link_to '编辑', edit_student_result_path(@student,@result) %> |
<%= link_to '返回所有成绩', student_results_path(@student) %>