config/routes.rb
# encoding: utf-8
Xmadweb::Application.routes.draw do


  # 考生的试卷
  # 作者： ryan
  # 添加时间: 2013-4-17
  # 修改添加看自己的试卷
  # 2013-4-18
  resources :vocabulary_exams do 
    # 试卷
    collection do
        post "save_voc"
    end
    get "my", :on => :collection
  end

  # 单词和意思
  # 作者： ryan
  # 添加时间: 2013-4-16
  resources :vocabularies  do 
    resources :vocabulary_meanings
  end
  # 显示个人的考试列表
  # 作者： ryan
  # 添加时间: 2013-4-18
  resources :word_child_categories do
    get "me", :on => :collection
  end

  # 单词类别
  # 作者： ryan
  # 添加时间: 2013-4-15
  # 修改时间： 2013-4-16
  # 添加三个方法
  resources :word_categories do 
    get 'list', :on => :collection
    resources :word_child_categories do 
      member do
        get 'upload_word'
        # 显示词表
        get "show_word"
      end

      collection do
        post 'save_upload'
        get "list"
        post "save_voc"
      end
    end
  end

  # 统计谷歌广告
  resources :google_analytics do
    get 'show_traffic', :on => :collection
    get 'user_index', :on => :collection
  end

  # 关联广告页面
  resources :web_pages do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end
  # 关联类类别
  resources :tag_categories  do
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  # 关联位置
  resources :positions  do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end

  # 关联活动
  resources :campaigns do 
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  #批量上传词汇
  get "upload_xml/index"
  post "upload_xml/upload_file"

  # 单词
  resources :words do
    # 每个单词有很多意思
    resources :meanings
    # 删除所有单词属性
    get 'delete_all', :on => :collection
  end

  # 试卷
  resources :papers do
    # 试卷里面的单词
    resources :paper_words
  end

  resources :exam_types

  resources :word_properties

  # 教学问题
  resources :teaching_problems do
    get 'closed', :on => :collection
  end
  # 教学问题的标签
  match 'teaching_problems/tags/:name' , :to => 'teaching_problems#search_by_tag_name', 
    :via => [:get], :as => "teaching_problems_by_tagname"

  # 教材
  resources :teaching_materials do
    # 所有的标签
    get 'alltags', :on => :collection
    # 用来级联选择的
    get 'tagselect', :on => :collection
    # 课程
    resources :lessons
  end
  # 教材的标签
  match 'teaching_materials/tags/:name' , :to => 'teaching_materials#search_by_tag_name', 
    :via => [:get], :as => "teaching_materials_by_tagname"

  namespace :admin do
      root :to => "base#index"
      resources :users do
        post 'activity', :on => :member
      end
  end
  # 学生功能管理
  resources :students do
    # 附加属性
    resources :ext_attributes
    # 成绩管理
    resources :results
    collection do
      get 'view'
      get 'my'
      get 'result_delay'
      get 'exam'
      get 'search_index'
    end   
    # 学生时间表追踪管理
    resources :student_timelines
    # 学生分配督导和客户经理
    resources :student_distributes
    # 学习计划
    resources :dairy_plans do
      # calendar的计划用到的json数据格式
      get 'get_plan_json', :on => :collection
      get 'get_plan_json_for_exam', :on => :collection
      get 'get_plan_json_for_mockexam', :on => :collection
      get 'get_result_json', :on => :collection
      # 课程内容
      resources :course_contents do 
        # 获取课程安排的event给fullcalendar使用
        get 'get_course_content_json', :on => :collection
      end
    end
    # student attend the exams
    resources :exams do
        get 'student', :on => :collection
        get 'todo_exam', :on => :collection
        get 'doing_exam', :on => :collection
        get 'done_exam', :on => :collection
        get 'corrected_exam', :on => :collection
        get 'never_done_exam', :on => :collection
    end
    #students have many result_papers
    resources :result_papers do
        resources :result_words
        get 'student', :on => :collection
    end
  end
  # 督导的学生
  match 'students/jpms/:id(.:format)', :to => 'students#jpms', :via => [:get], :as => "students_by_jpm"
  # 客户经理的学生
  match 'students/spms/:id(.:format)', :to => 'students#spms', :via => [:get], :as => "students_by_spm"
  # 学生成绩按日汇总查询
  match "students/results_by_day", :to => "results#all_by_day", :via => [:post], :as => "results_all_by_day"
  # 学生考情按日查询
  match "students/timelines_by_day", :to => "student_timelines#all_by_day", :via => [:post], :as => "student_timelines_all_by_day"

  
  root :to => "home#index"
  
  devise_for :users

  resources :clicks do
    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_position', :on => :collection
    post 'save_position', :on => :collection

    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_page', :on => :collection
    post 'save_page', :on => :collection

    get 'add_category', :on => :collection
    post 'save_category', :on => :collection

    get 'add_up_category', :on => :collection
    post 'save_up_category', :on => :collection


    get 'sum_campaign', :on => :collection
    get 'sum_position', :on => :collection
    get 'sum_page', :on => :collection
    get 'sum_category', :on => :collection
    get 'sum_child_category', :on => :collection
    get 'search_result', :on => :collection

    get 'core_customer', :on => :collection
    get 'referral_traffic', :on => :collection
    get 'organic_traffic', :on => :collection
    get 'index_campaign', :on => :collection
  end


  resources :advertisements
  
  match "adclick", :to => "adclick#index", :via => [:get]


end

app/models/result_paper.rb
class ResultPaper < ActiveRecord::Base
  has_many :result_words, :dependent => :destroy
  belongs_to :user
  belongs_to :paper
end

app/controllers/result_papers_controller.rb
class ResultPapersController < ApplicationController
#  before_filter :authorize_not_student!, :except => [:new, :create]
#  before_filter :authorize_activity!
  # GET /result_papers
  # GET /result_papers.json
  def index
    @student = User.find(params[:student_id])
    @result_papers = @student.result_papers.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @result_papers }
    end
  end

  # GET /result_papers/1
  # GET /result_papers/1.json
  def show
      @student = User.find(params[:student_id])
      @result_paper = ResultPaper.find(params[:id])
      @exam =  Exam.find(@result_paper.exam_id)
      @words = Word.joins(:paper_words).where(:paper_words =>{:paper_id => @exam.paper_id})

      respond_to do |format|
        format.html # show.html.erb
      end
  end

  # GET /result_papers/new
  # GET /result_papers/new.json
  def new
    @student = User.find(params[:student_id])
    @result_paper = @student.result_papers.new
    @exam =  Exam.find(params[:id])
    @words = Word.joins(:paper_words).where(:paper_words => {:paper_id => @exam.paper_id})

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result_paper }
    end
  end

  # GET /result_papers/1/edit
  def edit
    @student = User.find(params[:student_id])
    @result_paper = ResultPaper.find(params[:id])
  end

  # POST /result_papers
  # POST /result_papers.json
  def create
      word_id = params[:word_id]
      answer = params[:answer]
      @exam = Exam.find(params[:exam_id])

      @rpaper = ResultPaper.new(:exam_id => @exam.id, :paper_id => @exam.paper_id, :user_id => current_user.id)
      @rpaper.save

      # index is for array
      is_right = []
      word_id.size.times do |index|
          if !answer[index].to_s.strip.empty?
              rights = []
              Meaning.where("word_id = #{word_id[index]}").find_each do  |r|
                  rights << r.content
              end
              if rights.include?(answer[index].to_s.strip)
                  is_right << 1
              else
                  is_right << 2
              end
              rights = []
          else
              is_right << 0
          end
      end

      ResultWord.transaction do
          inserts = []
          word_id.size.times do |i|
              inserts.push "(#{is_right[i]}, #{word_id[i]}, '#{(answer[i].empty?)?"":answer[i]}', #{@rpaper.id})"
          end
          ResultWord.connection.execute "INSERT INTO result_words (is_right, word_id, answer, result_paper_id) values #{inserts.join(", ")}"
      end

      #generate the score
      all = ResultWord.where(:result_paper_id => @rpaper.id).count*1.00
      score = ResultWord.where(:is_right => 1,:result_paper_id => @rpaper.id).count

      @result_paper = ResultPaper.find(@rpaper.id)
      @result_paper.update_attributes(:score => score, :rate => (score/all)*100)
      @exam.update_attributes(:status => 2)

      respond_to do |format|
          format.html { redirect_to student_student_exams_path(params[:student_id]), notice: 'Result paper was successfully created.' }
      end
  
  end

  # 督导批改试卷
  def update
    @result_paper = ResultPaper.find(params[:id])
    result_paper_id = params[:id]
    @exam = Exam.find(@result_paper.exam_id)
    @student = User.find(params[:student_id])


    # receive datas
    add_new_meaning = params[:add_new_meaning]

    ResultWord.find_in_batches(:conditions => "is_right = 2 and result_paper_id = #{result_paper_id}") do |rp|
        is_right = "is_right"
        rp.each do |r|
            if r.word_id
                is_right << r.word_id.to_s
                is_right = params[:"#{is_right}"]
            else
                is_right = 0
            end
            r.update_attributes(:is_right =>  is_right)
            is_right = "is_right"
        end
    end
    # add  new meanings to the word
    if add_new_meaning != nil
        add_new_meaning.each do |word_id|
            @meaning = Meaning.new(:is_confirmed => 0, :word_id => word_id)
            @meaning.content = ResultWord.find_by_word_id(word_id).answer
            @meaning.save
        end
    end

    # regenerate the score
    all = ResultWord.where(:result_paper_id => result_paper_id).count*1.00
    score = ResultWord.where(:is_right => 1,:result_paper_id => result_paper_id).count

    @result_paper.update_attributes(:score => score, :rate => (score/all)*100)
    @exam.update_attributes(:status => 3)
    
    respond_to do |format|
        format.html { redirect_to student_result_papers_path(@student), :notice => "Correct by hand already!"}
    end
  end

  # DELETE /result_papers/1
  # DELETE /result_papers/1.json
  def destroy
    @student = User.find(params[:student_id])
    @result_paper = @student.result_papers.find(params[:id])
    @result_paper.destroy

    respond_to do |format|
      format.html { redirect_to student_result_papers_path(@student) }
      format.json { head :no_content }
    end
  end

  # show students score list
  def student
    @result_papers = ResultPaper.where(:user_id => params[:id])
    @user = User.find(@result_papers.first.user_id)
  end
  
end

app/views/result_papers/_form.html.erb
<%= form_for(@result_paper) do |f| %>
  <% if @result_paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result_paper.errors.count, "error") %> prohibited this result_paper from being saved:</h2>

      <ul>
      <% @result_paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paper_id %><br />
    <%= f.number_field :paper_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/result_papers/edit.html.erb
<h1>手动批改试卷</h1>
<%= link_to 'Back', student_result_papers_path(@student) %>
<script type="text/javascript">
    $(function(){
        $("div.holder").jPages({
            containerID : "itemContainer"
        });
  });
</script>

<style type="text/css">
    .main {
      display: table;
      border-collapse: collapse;
    }

    .nav {
      display: table-cell;
      width: 60px;
    }

    .extras {
      display: table-cell;
      width: 120px;
      padding-left: 10px;
    }

    .content {
      display: table-cell;
      width: 120px;
      padding-left: 10px;
    }
</style>
<%= form_tag("/students/#{@student.id}/result_papers/#{@result_paper.id}", :method => "put") do %>

<div class="holder"></div>
<div  class="main">
    <div class="nav">编号</div>
    <div class="extras">单词</div>
    <div class="extras">考生答案</div>
    <div class="extras">添加考生答案</div>
    <div class="extras">正确答案</div>
    <div class="extras">判断正误</div>
    <div class="extras">教师添加</div>
</div>
<br />
<div id="dialog" title="Add New Meaning">
    
</div>
<!-- display the paper -->
<% i=1 %>
<div id="itemContainer">
    <% @result_paper.result_words.each do |p| %>
    <div  class="main">
        <div class="nav"> <%= i %></div>
        <div class="extras"> <%= Word.find(p.word_id).content  %> </div>
        <% if p.answer.empty? %>
          <div class="extras">空</div>
        <% else%>
          <div class="content"> <%=  (p.answer.empty?)?"空":p.answer %></div>
        <% end %>
        <div class="extras">
          <% if (p.is_right==2)%>
            <%=  check_box_tag 'add_new_meaning[]', "#{p.word_id}" %>添加
          <% end %>
        </div>
        <div class="extras">
          <% Word.find(p.word_id).meanings.each do |f| %>
            <div><%= f.content %></div>
          <% end %>
        </div>
        <div class="extras">
          <% if p.is_right ==1 %>
            <%= "正确" %>
          <% elsif p.is_right ==2 %>
            <div>
              <input  name="is_right<%= p.word_id %>" type="radio" value="1" />正确|
              <input  name="is_right<%= p.word_id %>" type="radio" value="0" checked="true"/>错误
            </div>
          <%  end %>
        </div>
        <div class="extras">
          <% if p.is_right ==2 %>
            <input type="button" name="s3" value="添加" onclick="JqueryDialog.Open1('添加单词新意思', '<%= new_word_meaning_path(p.word_id) %>', 800, 400);" />
          <%  end %>
        </div>
        <% i = i+1 %>
    </div>
    <% end %>
</div>
<%= submit_tag  "确认批改", :confirm => "确定提交批改吗？" %>
<% end %>
<div class="holder"></div>

app/views/result_papers/index.html.erb
<h1>考试结果列表</h1>

<table>
    <tr>
        <th>试卷名称</th>
        <th>考生</th>
        <th>分数</th>
        <th>正确率</th>
        <th>试卷状态</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    <% @result_papers.each do |result_paper| %>
    <tr>
        <td><%= Paper.find(result_paper.paper_id).name %></td>
        <td><%= User.find(result_paper.user_id).name %></td>
        <td><%= result_paper.score %></td>
        <td><%= result_paper.rate %><%= (result_paper.rate== nil)?"":"%"%></td>
        <% exam = Exam.find(result_paper.exam_id) %>
        <% if exam.status == 0 %>
          <td><%="未开始" %></td>
          <td><%= link_to '查看试卷', student_result_paper_path(@student, result_paper) %></td>
        <% elsif exam.status == 1%>
          <td><%= "正在进行" %></td>
          <td><%= link_to '查看试卷', student_result_paper_path(@student, result_paper) %></td>
        <% elsif exam.status == 2%>
          <td><%= "已结束" %></td>
          <td><%= link_to '查看试卷', "/students/#{@student.id}/result_papers/#{result_paper.id}/result_words" %></td>
          <td><%= link_to '手动批改', edit_student_result_paper_path(@student, result_paper) %></td>
          <td><%= link_to '删除试卷', student_result_paper_path(@student, result_paper), confirm: 'Are you sure?', method: :delete %></td>
        <% elsif exam.status == 3%>
          <td><%= "已批改" %></td>
           <td><%= link_to '查看试卷', "/students/#{@student.id}/result_papers/#{result_paper.id}/result_words" %></td>
        <% elsif exam.status == 1%>
          <td><%= "未参加" %></td>
          <td><%= link_to '查看试卷', student_result_paper_path(@student, result_paper) %></td>
        <% else %>
          <td><%= "状态错误" %></td>
        <% end  %>
    </tr>
    <% end %>
</table>
<%=h will_paginate @result_papers, :previous_label => '上一页',  :next_label => '下一页'%>

app/views/result_papers/new.html.erb
<h1><%= @exam.paper.name%></h1>
<script type="text/javascript">
  $(function(){
    $("div.holder").jPages({
      containerID : "itemContainer"
    });
    $('#counter').countdown({
      format: 'mm:ss',
      startTime: "<%= @exam.set_time %>:00",
      digitImages: 6,
      digitWidth: 53,
      digitHeight: 77,
      timerEnd: function() {
         alert("Time out!");
         $("form").submit();
      },
      image: "/images/digits.png"
    });
 });
</script>

<style type="text/css">
  .main {
    display: table;
    border-collapse: collapse;
  }

  .nav {
    display: table-cell;
    width: 60px;
  }

  .extras {
    display: table-cell;
    width: 180px;
    padding-left: 10px;
    border-right: 1px dotted #d7ad7b;
  }

  .content {
    display: table-cell;
    width: 380px;
    padding-left: 10px;
  }

  .cntSeparator {
        font-size: 54px;
        margin: 10px 7px;
        color: #000;
      }
  .desc { margin: 7px 3px; }
  .desc div {
    float: left;
    font-family: Arial;
    width: 70px;
    margin-right: 65px;
    font-size: 13px;
    font-weight: bold;
    color: #000;
  }
</style>


<!-- show clock count-->
<div id="counter"></div>
<div class="desc">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
</div>


<div class="holder"></div>
<%= form_tag("/students/#{@student.id}/result_papers") do %>
<div id="itemContainer">
    <% @words.each do |p| %>
        <div class="main">
          <div class="extras">
            <%= p.content %>
          </div>
          <div class="content">
            <%= text_field_tag "answer[]" %>
          </div>
        </div>
        <%= hidden_field_tag "word_id[]", "#{p. id}" %>
    <%  end %>
    <%= hidden_field_tag 'exam_id', "#{@exam.id}"  %>
</div>


<div class="holder"></div>
    <%= submit_tag 'Submit exam', confirm: '确定提交试卷吗?' %>
<% end %>

app/views/result_papers/pre_show.html.erb
<script type="text/javascript">
    $(function(){
        $("div.holder").jPages({
            containerID : "itemContainer"
        });
    });
</script>

<style type="text/css">
    .main {
      display: table;
      border-collapse: collapse;
    }

    .nav {
      display: table-cell;
      width: 90px;
    }

    .extras {
      display: table-cell;
      width: 180px;
      padding-left: 10px;
      border-right: 1px dotted #d7ad7b;
    }

    .content {
      display: table-cell;
      width: 380px;
      padding-left: 10px;
      border-right: 1px dotted #d7ad7b;
      border-bottom: 1px dotted #d7ad7b;
    }
</style>
  <p>
  <b>试卷名称:</b>
    <%= @exam.paper.name %>
  </p>

  <p>
  <b>考生姓名:</b>
  <%= @student.name %>
  </p>

  <p>
  <b>总分:</b>
  <%= @result_paper.score %>
  </p>
  <p>
  <b>正确率:</b>
  <%= @result_paper.rate %><%= (@result_paper.rate == nil)?"":"%"%>
  </p>
  <p>
    <b>考试开始时间:</b>
    <%= @exam.start_time.strftime("%m-%d %H:%M") %>
  </p>
  <p>
  <b>考试结束时间</b>
  <%= @exam.finish_time.strftime("%m-%d %H:%M") %>
  </p>

  <div class="holder"></div>
  <div  class="main">
      <div class="nav">编号</div>
      <div class="extras">单词</div>
      <div class="content">right答案</div>
      <div class="content">考生答案</div>
  </div>
  <!-- display the paper -->
  <div id="itemContainer">
      <% @result_paper.result_words.each do |p| %>
      <div  class="main">
          <div class="nav"></div>
          <div class="extras"> <%= p.word.content  %> </div>
          <div class="content">
              <% p.word.meanings.each do |w|  %>
                  <div><%= w.content %></div>
              <% end %>
          </div>
          <div class="content"><%= p.answer %></div>
      </div>
      <% end %>
  </div>
  <div class="holder"></div>

app/views/result_papers/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', student_result_papers_path(@student) %>
<script type="text/javascript">
  $(function(){
      $("div.holder").jPages({
          containerID : "itemContainer"
      });
  });
</script>

<div>试卷名称:<%= @exam.paper.name %></div>
<div>考试时间:<%= @exam.set_time %>分钟</div>
<div>开始时间:<%= @exam.start_time.strftime("%Y:%H:%M")  %></div>
<div>结束时间:<%= @exam.finish_time.strftime("%Y:%H:%M") %></div>


<div class="holder"></div>
<!-- display the paper -->
<% i=1 %>
<div id="itemContainer">
<% @words.each do |word| %>
    <div> <%= i %> : <%= word.content  %>
          <% word.meanings.each do |ms| %>
              <%= ms.content %>
          <% end %>
    </div>
    <% i = i+1 %>
<% end %>
</div>
<div class="holder"></div>

app/views/result_papers/student.html.erb
<h1>考试结果列表</h1>
<div>考生:<%= @user.name %></div>
<table>
  <tr>
    <th>试卷名称</th>
    <th>分数</th>
    <th>正确率</th>
    <th>试卷状态</th>
    <th></th>
  </tr>

<% @result_papers.each do |result_paper| %>
  <tr>
    <td><%= Paper.find(result_paper.paper_id).name %></td>
    <td><%= result_paper.score %></td>
    <td><%= result_paper.rate %><%= (result_paper.rate== nil)?"":"%"%></td>

    <% if result_paper.status == 0 %>
      <td><%="未开始" %></td>
      <td><%= link_to '查看试卷', result_paper %></td>
    <% elsif result_paper.status == 1%>
      <td><%= "正在进行" %></td>
    <% elsif result_paper.status == 2%>
      <td><%= "已结束" %></td>
      <td><%= link_to '查看试卷', "/result_papers/pre_show?id=#{result_paper.id}" %></td>
      <td><%= link_to '手动批改', edit_result_paper_path(result_paper) %></td>
      <td><%= link_to '删除试卷', result_paper, confirm: 'Are you sure?', method: :delete %></td>
    <% elsif result_paper.status == 3%>
      <td><%= "Corrected" %></td>
      <td><%= link_to '查看试卷', "/result_papers/pre_show?id=#{result_paper.id}" %></td>
    <% else %>
      <td><%= "状态错误" %></td>
    <% end  %>
  </tr>
<% end %>
</table>