config/routes.rb
# encoding: utf-8
Xmadweb::Application.routes.draw do


  # 考生的试卷
  # 作者： ryan
  # 添加时间: 2013-4-17
  # 修改添加看自己的试卷
  # 2013-4-18
  resources :vocabulary_exams do 
    # 试卷
    collection do
        post "save_voc"
    end
    get "my", :on => :collection
  end

  # 单词和意思
  # 作者： ryan
  # 添加时间: 2013-4-16
  resources :vocabularies  do 
    resources :vocabulary_meanings
  end
  # 显示个人的考试列表
  # 作者： ryan
  # 添加时间: 2013-4-18
  resources :word_child_categories do
    get "me", :on => :collection
  end

  # 单词类别
  # 作者： ryan
  # 添加时间: 2013-4-15
  # 修改时间： 2013-4-16
  # 添加三个方法
  resources :word_categories do 
    get 'list', :on => :collection
    resources :word_child_categories do 
      member do
        get 'upload_word'
        # 显示词表
        get "show_word"
      end

      collection do
        post 'save_upload'
        get "list"
        post "save_voc"
      end
    end
  end

  # 统计谷歌广告
  resources :google_analytics do
    get 'show_traffic', :on => :collection
    get 'user_index', :on => :collection
  end

  # 关联广告页面
  resources :web_pages do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end
  # 关联类类别
  resources :tag_categories  do
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  # 关联位置
  resources :positions  do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end

  # 关联活动
  resources :campaigns do 
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  #批量上传词汇
  get "upload_xml/index"
  post "upload_xml/upload_file"

  # 单词
  resources :words do
    # 每个单词有很多意思
    resources :meanings
    # 删除所有单词属性
    get 'delete_all', :on => :collection
  end

  # 试卷
  resources :papers do
    # 试卷里面的单词
    resources :paper_words
  end

  resources :exam_types

  resources :word_properties

  # 教学问题
  resources :teaching_problems do
    get 'closed', :on => :collection
  end
  # 教学问题的标签
  match 'teaching_problems/tags/:name' , :to => 'teaching_problems#search_by_tag_name', 
    :via => [:get], :as => "teaching_problems_by_tagname"

  # 教材
  resources :teaching_materials do
    # 所有的标签
    get 'alltags', :on => :collection
    # 用来级联选择的
    get 'tagselect', :on => :collection
    # 课程
    resources :lessons
  end
  # 教材的标签
  match 'teaching_materials/tags/:name' , :to => 'teaching_materials#search_by_tag_name', 
    :via => [:get], :as => "teaching_materials_by_tagname"

  namespace :admin do
      root :to => "base#index"
      resources :users do
        post 'activity', :on => :member
      end
  end
  # 学生功能管理
  resources :students do
    # 附加属性
    resources :ext_attributes
    # 成绩管理
    resources :results
    collection do
      get 'view'
      get 'my'
      get 'result_delay'
      get 'exam'
      get 'search_index'
    end   
    # 学生时间表追踪管理
    resources :student_timelines
    # 学生分配督导和客户经理
    resources :student_distributes
    # 学习计划
    resources :dairy_plans do
      # calendar的计划用到的json数据格式
      get 'get_plan_json', :on => :collection
      get 'get_plan_json_for_exam', :on => :collection
      get 'get_plan_json_for_mockexam', :on => :collection
      get 'get_result_json', :on => :collection
      # 课程内容
      resources :course_contents do 
        # 获取课程安排的event给fullcalendar使用
        get 'get_course_content_json', :on => :collection
      end
    end
    # student attend the exams
    resources :exams do
        get 'student', :on => :collection
        get 'todo_exam', :on => :collection
        get 'doing_exam', :on => :collection
        get 'done_exam', :on => :collection
        get 'corrected_exam', :on => :collection
        get 'never_done_exam', :on => :collection
    end
    #students have many result_papers
    resources :result_papers do
        resources :result_words
        get 'student', :on => :collection
    end
  end
  # 督导的学生
  match 'students/jpms/:id(.:format)', :to => 'students#jpms', :via => [:get], :as => "students_by_jpm"
  # 客户经理的学生
  match 'students/spms/:id(.:format)', :to => 'students#spms', :via => [:get], :as => "students_by_spm"
  # 学生成绩按日汇总查询
  match "students/results_by_day", :to => "results#all_by_day", :via => [:post], :as => "results_all_by_day"
  # 学生考情按日查询
  match "students/timelines_by_day", :to => "student_timelines#all_by_day", :via => [:post], :as => "student_timelines_all_by_day"

  
  root :to => "home#index"
  
  devise_for :users

  resources :clicks do
    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_position', :on => :collection
    post 'save_position', :on => :collection

    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_page', :on => :collection
    post 'save_page', :on => :collection

    get 'add_category', :on => :collection
    post 'save_category', :on => :collection

    get 'add_up_category', :on => :collection
    post 'save_up_category', :on => :collection


    get 'sum_campaign', :on => :collection
    get 'sum_position', :on => :collection
    get 'sum_page', :on => :collection
    get 'sum_category', :on => :collection
    get 'sum_child_category', :on => :collection
    get 'search_result', :on => :collection

    get 'core_customer', :on => :collection
    get 'referral_traffic', :on => :collection
    get 'organic_traffic', :on => :collection
    get 'index_campaign', :on => :collection
  end


  resources :advertisements
  
  match "adclick", :to => "adclick#index", :via => [:get]


end

app/models/teaching_problem.rb
# encoding: utf-8
# 教学问题
class TeachingProblem < ActiveRecord::Base
  belongs_to :teacher, :class_name => "User",
      :foreign_key => "teacher_id"
  belongs_to :student, :class_name => "User",
      :foreign_key => "student_id"
  # 添加标签的功能
  acts_as_taggable
  # 考试标签 科目标签
  acts_as_taggable_on :subjects, :depts
  
  def problem_type_str
    case problem_type
      when 0
        "其他"
      when 1
        "学生作业未完成"
      when 2
        "学生测试未完成"
      when 3
        "学生迟到或者早退"
      when 4
        "老师没有批改或提交"
      when 5
        "老师没有布置作业或侧试"
      when 6
        "单词不合格"
      when 7
        "测试不合格"
    end
  end
end

app/controllers/teaching_problems_controller.rb
# encoding: utf-8
# 教学问题
class TeachingProblemsController < ApplicationController
  before_filter :authorize_not_student!
  before_filter :authorize_activity!
  # GET /teaching_problems
  # GET /teaching_problems.json
  def index
    @teaching_problems = TeachingProblem.where(:sloved => false).order("created_at DESC").paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teaching_problems }
    end
  end

  # GET /teaching_problems/1
  # GET /teaching_problems/1.json
  def show
    @teaching_problem = TeachingProblem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teaching_problem }
    end
  end
  
  # 按名称搜索
  def search_by_tag_name
    @teaching_problems = TeachingProblem.tagged_with(params[:name], :any => true).paginate(:page => params[:page], :per_page => 20)
    @tagname = params[:name]
  end
  # 已经关闭的问题
  def closed
    @teaching_problems = TeachingProblem.where(:sloved => true).order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
  end

  # GET /teaching_problems/new
  # GET /teaching_problems/new.json
  def new
    @students = User.where(:role => 1, :is_activity => true).order("email DESC")
    @teachers = User.where(:role => 2, :is_activity => true).order("email DESC")
    @teaching_problem = TeachingProblem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teaching_problem }
    end
  end

  # GET /teaching_problems/1/edit
  def edit
    @students = User.where(:role => 1, :is_activity => true).order("email DESC")
    @teachers = User.where(:role => 2, :is_activity => true).order("email DESC")
    @teaching_problem = TeachingProblem.find(params[:id])
  end

  # POST /teaching_problems
  # POST /teaching_problems.json
  def create
    @teaching_problem = TeachingProblem.new(params[:teaching_problem])
    #@teaching_problem.student = User.find(params[:student])
    #@teaching_problem.teacher = User.find(params[:teacher])
    respond_to do |format|
      if @teaching_problem.save
        format.html { redirect_to @teaching_problem, notice: 'Teaching problem was successfully created.' }
        format.json { render json: @teaching_problem, status: :created, location: @teaching_problem }
      else
        format.html { render action: "new" }
        format.json { render json: @teaching_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teaching_problems/1
  # PUT /teaching_problems/1.json
  def update
    @teaching_problem = TeachingProblem.find(params[:id])

    respond_to do |format|
      if @teaching_problem.update_attributes(params[:teaching_problem])
        format.html { redirect_to @teaching_problem, notice: 'Teaching problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teaching_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaching_problems/1
  # DELETE /teaching_problems/1.json
  def destroy
    @teaching_problem = TeachingProblem.find(params[:id])
    @teaching_problem.destroy

    respond_to do |format|
      format.html { redirect_to teaching_problems_url }
      format.json { head :no_content }
    end
  end
end

app/views/teaching_problems/_form.html.erb
<%= form_for(@teaching_problem) do |f| %>
  <% if @teaching_problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teaching_problem.errors.count, "error") %> prohibited this teaching_problem from being saved:</h2>

      <ul>
      <% @teaching_problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  
  <p>
	<h6>选择学生</h6>
	<% @students.each do |student| %>	
  	<%= f.radio_button(:student_id, student.id) %>
	<%= f.label :student_id, student.name %>
	<% end %>
  </p>

  <p>
	<h6>选择老师</h6>
	<% @teachers.each do |teacher| %>	
  	<%= f.radio_button(:teacher_id, teacher.id) %>
	<%= f.label :teacher_id, teacher.name %>
	<% end %>
  </p>

  <p>
	<h6>问题科目</h6>	
  	<%= f.radio_button(:subject_list, "听力") %>
	<%= f.label :subject_list, "听力" %>
	<%= f.radio_button(:subject_list, "阅读") %>
	<%= f.label :subject_list, "阅读" %>
	<%= f.radio_button(:subject_list, "口语") %>
	<%= f.label :subject_list, "口语" %>
	<%= f.radio_button(:subject_list, "写作") %>
	<%= f.label :subject_list, "写作" %>
	<%= f.radio_button(:subject_list, "单词") %>
	<%= f.label :subject_list, "单词" %>
	<%= f.radio_button(:subject_list, "其他") %>
	<%= f.label :subject_list, "其他" %>
  </p>

  <p>
	<h6>问题部门</h6>	
  	<%= f.radio_button(:dept_list, "督导") %>
	<%= f.label :dept_list, "督导" %>
	<%= f.radio_button(:dept_list, "教学") %>
	<%= f.label :dept_list, "教学" %>
	<%= f.radio_button(:dept_list, "质检") %>
	<%= f.label :dept_list, "质检" %>
	<%= f.radio_button(:dept_list, "其他") %>
	<%= f.label :dept_list, "其他" %>
  </p>

  <p>
	<h6>问题类型</h6>	
  	<%= f.radio_button(:problem_type, 1) %>
	<%= f.label :problem_type, "学生作业未完成" %>
	<br>
	<%= f.radio_button(:problem_type, 2) %>
	<%= f.label :problem_type, "学生测试未完成" %>
	<br>
	<%= f.radio_button(:problem_type, 3) %>
	<%= f.label :problem_type, "学生迟到或者早退" %>
	<br>
	<%= f.radio_button(:problem_type, 4) %>
	<%= f.label :problem_type, "老师没有批改或提交" %>
	<br>
	<%= f.radio_button(:problem_type, 5) %>
	<%= f.label :problem_type, "老师没有布置作业或侧试" %>
	<br>
	<%= f.radio_button(:problem_type, 6) %>
	<%= f.label :problem_type, "单词不合格" %>
	<br>
	<%= f.radio_button(:problem_type, 7) %>
	<%= f.label :problem_type, "测试不合格" %>
	<br>
	<%= f.radio_button(:problem_type, 0) %>
	<%= f.label :problem_type, "其他情况" %>
	<br>
  </p>


  
  
  <p>
	<h6>问题详细描述或者补充</h6>	
  	<%= f.text_area(:problem_spec, :cols => 100, :rows => 10) %>
  </p>

  <hr>

  <p>
		<%= f.check_box  :sloved %>
		<%= f.label :sloved	, '已解决,关闭' %>			
  </p>

  <p>
	<h6>解决方法或者描述</h6>	
  	<%= f.text_area(:slove_spec, :cols => 100, :rows => 10) %>
  </p>

  <div class="actions">
    <%= f.submit "保存" %>
  </div>
<% end %>

app/views/teaching_problems/closed.html.erb
<h1>已经关闭的教学问题</h1>

<table>
  <tr>
    <th>日期</th>
    <th>学生</th>
	<th>督导</th>
	<th>经理</th>
	<th>教师</th>
	<th>问题部门</th>
	<th>科目</th>
	<th>问题类型</th>
    <th>操作</th>
  </tr>

<% @teaching_problems.each do |teaching_problem| %>
  <tr>
	<td>
		<%= teaching_problem.created_at.strftime('%Y-%m-%d') %>
	</td>
	<td>
		<%= link_to teaching_problem.student.name , student_path(teaching_problem.student.id)%>
	</td>
	<td>
		<% if teaching_problem.student.jpm %>
			<%= teaching_problem.student.jpm.name%>
		<% else %>
			<a href="/students/<%= teaching_problem.student.id %>/student_distributes">现在分配</a>
		<% end %>
	</td>
	<td>
		<% if teaching_problem.student.spm %>
			<%= teaching_problem.student.spm.name%>
		<% else %>
			<a href="/students/<%= teaching_problem.student.id %>/student_distributes">现在分配</a>
		<% end %>
	</td>
	
	<td>
		<%= teaching_problem.teacher ? teaching_problem.teacher.name : ""%>
	</td>
	<td>
		<%= link_to teaching_problem.dept_list, teaching_problems_by_tagname_path(teaching_problem.dept_list) %>
	</td>
	<td>
		<%= link_to teaching_problem.subject_list, teaching_problems_by_tagname_path(teaching_problem.subject_list) %>
	</td>
	<td>
		<%= teaching_problem.problem_type_str %>
	</td>
    <td>
		<%= link_to '查看', teaching_problem %>
		|
    	<%= link_to '编辑或关闭', edit_teaching_problem_path(teaching_problem) %>
		|
    	<%= link_to '删除', teaching_problem, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%=h will_paginate @users, :previous_label => '上一页',  :next_label => '下一页'%>
<br />

<%= link_to '新建问题', new_teaching_problem_path %>

app/views/teaching_problems/edit.html.erb
<h1>编辑教学问题</h1>

<%= render 'form' %>

<%= link_to '查看', @teaching_problem %> |
<%= link_to '返回', teaching_problems_path %>

app/views/teaching_problems/index.html.erb
<h1>所有教学问题</h1>
<hr>
<h6>问题快速导航:
<%= link_to "已关闭的" , closed_teaching_problems_path %>
|
<%= link_to "听力" , teaching_problems_by_tagname_path("听力") %>
|
<%= link_to "阅读" , teaching_problems_by_tagname_path("阅读") %>
|
<%= link_to "口语" , teaching_problems_by_tagname_path("口语") %>
|
<%= link_to "写作" , teaching_problems_by_tagname_path("写作") %>
|
<%= link_to "单词" , teaching_problems_by_tagname_path("单词") %>
|
<%= link_to "教学部门", teaching_problems_by_tagname_path("教学") %>
|
<%= link_to "督导部门", teaching_problems_by_tagname_path("督导") %>
|
<%= link_to "质检部门", teaching_problems_by_tagname_path("质检") %>
</h6>

<table>
  <tr>
    <th>日期</th>
    <th>学生</th>
	<th>督导</th>
	<th>经理</th>
	<th>教师</th>
	<th>问题部门</th>
	<th>科目</th>
	<th>问题类型</th>
    <th>操作</th>
  </tr>

<% @teaching_problems.each do |teaching_problem| %>
  <tr>
	<td>
		<%= teaching_problem.created_at.strftime('%Y-%m-%d') %>
	</td>
	<td>
		<%= link_to teaching_problem.student.name , student_path(teaching_problem.student.id)%>
	</td>
	<td>
		<% if teaching_problem.student.jpm %>
			<%= teaching_problem.student.jpm.name%>
		<% else %>
			<a href="/students/<%= teaching_problem.student.id %>/student_distributes">现在分配</a>
		<% end %>
	</td>
	<td>
		<% if teaching_problem.student.spm %>
			<%= teaching_problem.student.spm.name%>
		<% else %>
			<a href="/students/<%= teaching_problem.student.id %>/student_distributes">现在分配</a>
		<% end %>
	</td>
	
	<td>
		<%= teaching_problem.teacher ? teaching_problem.teacher.name : ""%>
	</td>
	<td>
		<%= link_to teaching_problem.dept_list, teaching_problems_by_tagname_path(teaching_problem.dept_list) %>
	</td>
	<td>
		<%= link_to teaching_problem.subject_list, teaching_problems_by_tagname_path(teaching_problem.subject_list) %>
	</td>
	<td>
		<%= teaching_problem.problem_type_str %>
	</td>
    <td>
		<%= link_to '查看', teaching_problem %>
		|
    	<%= link_to '编辑或关闭', edit_teaching_problem_path(teaching_problem) %>
		|
    	<%= link_to '删除', teaching_problem, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%=h will_paginate @users, :previous_label => '上一页',  :next_label => '下一页'%>
<br />

<%= link_to '新建问题', new_teaching_problem_path %>

app/views/teaching_problems/new.html.erb
<h1>创建教学问题</h1>

<%= render 'form' %>

<%= link_to '返回', teaching_problems_path %>

app/views/teaching_problems/search_by_tag_name.html.erb
<h1>所有<%= @tagname %>的教学问题</h1>

<table>
  <tr>
    <th>日期</th>
    <th>学生</th>
	<th>督导</th>
	<th>经理</th>
	<th>教师</th>
	<th>问题部门</th>
	<th>科目</th>
	<th>问题类型</th>
    <th>操作</th>
  </tr>

<% @teaching_problems.each do |teaching_problem| %>
  <tr>
	<td>
		<%= teaching_problem.created_at.strftime('%Y-%m-%d') %>
	</td>
	<td>
		<%= link_to teaching_problem.student.name , student_path(teaching_problem.student.id)%>
	</td>
	<td>
		<% if teaching_problem.student.jpm %>
			<%= teaching_problem.student.jpm.name%>
		<% else %>
			<a href="/students/<%= teaching_problem.student.id %>/student_distributes">现在分配</a>
		<% end %>
	</td>
	<td>
		<% if teaching_problem.student.spm %>
			<%= teaching_problem.student.spm.name%>
		<% else %>
			<a href="/students/<%= teaching_problem.student.id %>/student_distributes">现在分配</a>
		<% end %>
	</td>
	
	<td>
		<%= teaching_problem.teacher ? teaching_problem.teacher.name : ""%>
	</td>
	<td>
		<%= link_to teaching_problem.dept_list, teaching_problems_by_tagname_path(teaching_problem.dept_list) %>
	</td>
	<td>
		<%= link_to teaching_problem.subject_list, teaching_problems_by_tagname_path(teaching_problem.subject_list) %>
	</td>
	<td>
		<%= teaching_problem.problem_type_str %>
	</td>
    <td>
		<%= link_to '查看', teaching_problem %>
		|
    	<%= link_to '编辑或关闭', edit_teaching_problem_path(teaching_problem) %>
		|
    	<%= link_to '删除', teaching_problem, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%=h will_paginate @users, :previous_label => '上一页',  :next_label => '下一页'%>
<br />

<%= link_to '新建问题', new_teaching_problem_path %>

app/views/teaching_problems/show.html.erb
<p>
	<h6>日期:</h6><%= @teaching_problem.created_at.strftime('%Y-%m-%d') %>
	<h6>学生:</h6><%= link_to @teaching_problem.student.name , student_path(@teaching_problem.student.id)%>
	<h6>教师:</h6><%= @teaching_problem.teacher ? @teaching_problem.teacher.name : ""%>
	
	<h6>督导:</h6>
	<% if @teaching_problem.student.jpm %>
		<%= @teaching_problem.student.jpm.name%>
	<% else %>
		<a href="/students/<%= @teaching_problem.student.id %>/student_distributes">现在分配</a>
	<% end %>

    <h6>经理:</h6>
	<% if @teaching_problem.student.spm %>
		<%= @teaching_problem.student.spm.name%>
	<% else %>
		<a href="/students/<%= @teaching_problem.student.id %>/student_distributes">现在分配</a>
	<% end %>
	<h6>问题部门:</h6><%= link_to @teaching_problem.dept_list, teaching_problems_by_tagname_path(@teaching_problem.dept_list) %>
	<h6>问题科目:</h6><%= link_to @teaching_problem.subject_list, teaching_problems_by_tagname_path(@teaching_problem.subject_list) %>
	<h6>问题类型:</h6><%= @teaching_problem.problem_type_str %>
	<h6>问题描述:</h6><%= @teaching_problem.problem_spec %>
	<h6><%= @teaching_problem.sloved ? "已关闭" : "未关闭" %></h6>
	<h6>解决描述:</h6><%= @teaching_problem.slove_spec %>
	
</td>
</p>

<%= link_to '编辑', edit_teaching_problem_path(@teaching_problem) %> |
<%= link_to '返回', teaching_problems_path %>