config/routes.rb
# encoding: utf-8
Xmadweb::Application.routes.draw do


  # 考生的试卷
  # 作者： ryan
  # 添加时间: 2013-4-17
  # 修改添加看自己的试卷
  # 2013-4-18
  resources :vocabulary_exams do 
    # 试卷
    collection do
        post "save_voc"
    end
    get "my", :on => :collection
  end

  # 单词和意思
  # 作者： ryan
  # 添加时间: 2013-4-16
  resources :vocabularies  do 
    resources :vocabulary_meanings
  end
  # 显示个人的考试列表
  # 作者： ryan
  # 添加时间: 2013-4-18
  resources :word_child_categories do
    get "me", :on => :collection
  end

  # 单词类别
  # 作者： ryan
  # 添加时间: 2013-4-15
  # 修改时间： 2013-4-16
  # 添加三个方法
  resources :word_categories do 
    get 'list', :on => :collection
    resources :word_child_categories do 
      member do
        get 'upload_word'
        # 显示词表
        get "show_word"
      end

      collection do
        post 'save_upload'
        get "list"
        post "save_voc"
      end
    end
  end

  # 统计谷歌广告
  resources :google_analytics do
    get 'show_traffic', :on => :collection
    get 'user_index', :on => :collection
  end

  # 关联广告页面
  resources :web_pages do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end
  # 关联类类别
  resources :tag_categories  do
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  # 关联位置
  resources :positions  do
    get 'all', :on => :collection
    get 'detail', :on => :collection
  end

  # 关联活动
  resources :campaigns do 
    get 'detail', :on => :collection
    get 'all', :on => :collection
  end

  #批量上传词汇
  get "upload_xml/index"
  post "upload_xml/upload_file"

  # 单词
  resources :words do
    # 每个单词有很多意思
    resources :meanings
    # 删除所有单词属性
    get 'delete_all', :on => :collection
  end

  # 试卷
  resources :papers do
    # 试卷里面的单词
    resources :paper_words
  end

  resources :exam_types

  resources :word_properties

  # 教学问题
  resources :teaching_problems do
    get 'closed', :on => :collection
  end
  # 教学问题的标签
  match 'teaching_problems/tags/:name' , :to => 'teaching_problems#search_by_tag_name', 
    :via => [:get], :as => "teaching_problems_by_tagname"

  # 教材
  resources :teaching_materials do
    # 所有的标签
    get 'alltags', :on => :collection
    # 用来级联选择的
    get 'tagselect', :on => :collection
    # 课程
    resources :lessons
  end
  # 教材的标签
  match 'teaching_materials/tags/:name' , :to => 'teaching_materials#search_by_tag_name', 
    :via => [:get], :as => "teaching_materials_by_tagname"

  namespace :admin do
      root :to => "base#index"
      resources :users do
        post 'activity', :on => :member
      end
  end
  # 学生功能管理
  resources :students do
    # 附加属性
    resources :ext_attributes
    # 成绩管理
    resources :results
    collection do
      get 'view'
      get 'my'
      get 'result_delay'
      get 'exam'
      get 'search_index'
    end   
    # 学生时间表追踪管理
    resources :student_timelines
    # 学生分配督导和客户经理
    resources :student_distributes
    # 学习计划
    resources :dairy_plans do
      # calendar的计划用到的json数据格式
      get 'get_plan_json', :on => :collection
      get 'get_plan_json_for_exam', :on => :collection
      get 'get_plan_json_for_mockexam', :on => :collection
      get 'get_result_json', :on => :collection
      # 课程内容
      resources :course_contents do 
        # 获取课程安排的event给fullcalendar使用
        get 'get_course_content_json', :on => :collection
      end
    end
    # student attend the exams
    resources :exams do
        get 'student', :on => :collection
        get 'todo_exam', :on => :collection
        get 'doing_exam', :on => :collection
        get 'done_exam', :on => :collection
        get 'corrected_exam', :on => :collection
        get 'never_done_exam', :on => :collection
    end
    #students have many result_papers
    resources :result_papers do
        resources :result_words
        get 'student', :on => :collection
    end
  end
  # 督导的学生
  match 'students/jpms/:id(.:format)', :to => 'students#jpms', :via => [:get], :as => "students_by_jpm"
  # 客户经理的学生
  match 'students/spms/:id(.:format)', :to => 'students#spms', :via => [:get], :as => "students_by_spm"
  # 学生成绩按日汇总查询
  match "students/results_by_day", :to => "results#all_by_day", :via => [:post], :as => "results_all_by_day"
  # 学生考情按日查询
  match "students/timelines_by_day", :to => "student_timelines#all_by_day", :via => [:post], :as => "student_timelines_all_by_day"

  
  root :to => "home#index"
  
  devise_for :users

  resources :clicks do
    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_position', :on => :collection
    post 'save_position', :on => :collection

    get 'add_campaign', :on => :collection
    post 'save_campaign', :on => :collection

    get 'add_page', :on => :collection
    post 'save_page', :on => :collection

    get 'add_category', :on => :collection
    post 'save_category', :on => :collection

    get 'add_up_category', :on => :collection
    post 'save_up_category', :on => :collection


    get 'sum_campaign', :on => :collection
    get 'sum_position', :on => :collection
    get 'sum_page', :on => :collection
    get 'sum_category', :on => :collection
    get 'sum_child_category', :on => :collection
    get 'search_result', :on => :collection

    get 'core_customer', :on => :collection
    get 'referral_traffic', :on => :collection
    get 'organic_traffic', :on => :collection
    get 'index_campaign', :on => :collection
  end


  resources :advertisements
  
  match "adclick", :to => "adclick#index", :via => [:get]


end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :paper
  belongs_to :user
end

app/models/exam_type.rb
class ExamType < ActiveRecord::Base
  has_many :papers, :dependent => :destroy
end

app/controllers/exams_controller.rb
# encoding: utf-8
class ExamsController < ApplicationController
  before_filter :authorize_not_student!, :except => [:show, :student, :todo_exam, :doing_exam, :done_exam, :never_done_exam, :corrected_exam]
  before_filter :authorize_activity!
  # GET /exams
  # GET /exams.json
  def index
    @student = User.find(params[:student_id])
    @exams = @student.exams.order("start_time desc").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exams }
    end
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @student = User.find(params[:student_id])
    @exam =  Exam.find(params[:id])
    @words = Word.joins(:paper_words).where(:paper_words =>{:paper_id => @exam.paper_id})
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exam }
    end
  end

  # GET /exams/new
  # GET /exams/new.json
  def new
#    @student = User.find(params[:student_id])
    @exam = Exam.new
    @papers = Paper.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exam }
    end
  end

  # GET /exams/1/edit
  def edit
    @exam = Exam.find(params[:id])
  end

  # POST /exams
  # POST /exams.json
  def create
    @user = User.find(params[:student_id])
    date1 = DateTime.strptime(params[:exam]['start_time'] + " CCT", "%Y-%m-%d %H:%M %Z")

    date2 = date1.advance(:minutes => params[:exam]['set_time'].to_i)
    params[:exam]['start_time'] = date1
    params[:exam]['finish_time'] = date2
    params[:exam]['status'] = 0

    @exam = Exam.new(params[:exam])
    @exam.user = @user
    
    respond_to do |format|
      if @exam.save
        format.html { redirect_to student_exams_path(@user), notice: 'Exam was successfully created.' }
        format.json { render json: @exam, status: :created, location: @exam }
      else
        format.html { render action: "new" }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exams/1
  # PUT /exams/1.json
  def update
    @exam = Exam.find(params[:id])

    respond_to do |format|
      if @exam.update_attributes(params[:exam])
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @student = User.find(params[:student_id])
    @exam = @student.exams.find(params[:id])
    @rp = ResultPaper.find_by_exam_id(@exam.id)
    if @rp
        @rp.result_words.destroy
        @rp.destroy
    end
    @exam.destroy

    respond_to do |format|
      format.html { redirect_to student_exams_path(@student) }
      format.json { head :no_content }
    end
  end

  #  exams for student
  def student
  end

  # 即将参加的考试
  def todo_exam
      cur_time = DateTime.now().in_time_zone('Beijing')
      @todo_exams = Exam.where("user_id = ? and start_time > ?", current_user.id, "#{cur_time}").order("start_time desc").paginate(:page => params[:page], :per_page => 10)
  end

  # 正在进行的考试
  def doing_exam
      @cur_time = DateTime.now().in_time_zone('Beijing')
      @doing = Exam.where("user_id = ? and start_time <= ? and finish_time >= ? and status = 0 ", current_user.id, "#{@cur_time}", "#{@cur_time}").order("start_time desc").paginate(:page => params[:page], :per_page => 10)
      @doing.each do |exam|
        exam.update_attributes(:status => 1)
      end
      @doing_exams = Exam.where("user_id = ? and start_time <= ? and finish_time >= ? and status=1", current_user.id, "#{@cur_time}", "#{@cur_time}").order("start_time desc").paginate(:page => params[:page], :per_page => 10)
  end

  # 已经完成，没出分的考试
  def done_exam
      @done_exams = Exam.where("user_id = ? and status = 2", current_user.id).order("start_time desc").paginate(:page => params[:page], :per_page => 10)
  end

  # 已经完成，没出分的考试
  def never_done_exam
      cur_time = DateTime.now().in_time_zone('Beijing')
      @done = Exam.where("user_id = ? and finish_time < ? and status in (0, 1)", current_user.id, "#{cur_time}").order("start_time desc").paginate(:page => params[:page], :per_page => 10)
      @done.each do |exam|
        exam.update_attributes(:status => 4)
      end
      @never_done_exams = Exam.where("user_id = ? and status = 4 ", current_user.id).order("start_time desc").paginate(:page => params[:page], :per_page => 10)
  end

  # 已经批改的考试
  def corrected_exam
      cur_time = DateTime.now().in_time_zone('Beijing')
      @corrected_exams = Exam.where("user_id = ? and  status = 3", current_user.id).order("start_time desc").paginate(:page => params[:page], :per_page => 10)
  end

end

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <script>
          $(function() {
                  $( "#datepicker_1" ).datetimepicker();
                  $( "#datepicker_1" ).datetimepicker( "option", "dateFormat", "yy-mm-dd" );
          });
  </script>
  <div class="field">
    <%= f.label :paper_id %><br />
    <%= f.number_field :paper_id %>
  </div>

  <div class="field">
    <%= f.label :start_time, '考试开始时间:'%><br />
    <input type="text" id="datepicker_1" name="exam[start_time]" />
  </div>

  <div class="field">
    <%= f.label :set_time, "设定时间(min)"%><br />
	<%= f.select(:set_time, [['10', 10],['15', 15],['20', 20],['25', 25],['30', 30]])  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/corrected_exam.html.erb
<h1>已批改考试</h1>

<%= link_to "Back", student_student_exams_path(current_user)%>
<table>
<% @corrected_exams.each do |p| %>
    <% @rp = ResultPaper.find_by_exam_id(p.id) %>
    <tr>
        <td><%= link_to p.paper.name, "/students/#{current_user.id}/result_papers/#{@rp.id}/result_words" %></td>
        <td><%= p.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td>分数:<%= @rp.score %></td>
    </tr>
<% end %>
</table>
<%=h will_paginate @corrected_exams, :previous_label => '上一页',  :next_label => '下一页'%>

app/views/exams/doing_exam.html.erb
<h1>正在进行的考试</h1>
<%= link_to "Back", student_student_exams_path(current_user)%>
<div>当前时间：<%= @cur_time.strftime("%Y-%m-%d %H:%M")  %></div>
<table>
<% @doing_exams.each do |p| %>
    <tr>
        <td><%= link_to p.paper.name, "/students/#{current_user.id}/result_papers/new?id=#{p.id}" %></td>
        <td><%= p.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td></td>
    </tr>
<% end %>
</table>
<%=h will_paginate @doing_exams, :previous_label => '上一页',  :next_label => '下一页'%>

app/views/exams/done_exam.html.erb
<h1>已完成的考试</h1>

<%= link_to "Back", student_student_exams_path(current_user)%>
<table>
<% @done_exams.each do |p| %>
    <tr>
        <td><%= p.paper.name %></td>
        <td><%= p.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td>分数:未出分</td>
    </tr>
<% end %>
</table>
<%=h will_paginate @done_exams, :previous_label => '上一页',  :next_label => '下一页'%>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<h1>考试列表</h1>
<script type="text/javascript">
    $(function(){
        var date_now = new Date().getTime();
        $('.endTime').each(function(){
                  if((date_now/1000 - $(this).html())> 0){
                      $(this).parent().css('color','red');
                  }else{
                      $(this).parent().css('color', '#364')
                  }
        });
    })
</script>
<%= link_to '新建一次考试', new_student_exam_path(@student) %>
<table>
    <tr>
        <th>试卷名称</th>
        <th>开始时间</th>
        <th>时间(min)</th>
        <th>分数</th>
        <th>正确率</th>
        <th>状态</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <% @exams.each do |exam| %>
    <% @rp = ResultPaper.find_by_exam_id(exam.id) %>
    <tr class="change_color">
        <td><%= exam.paper.name %></td>
        <td><%= exam.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td class="endTime" style="display:none;"><%= exam.finish_time.to_i %></td>
        <td><%= exam.set_time %></td>
        <td><% if @rp %><%= @rp.score %><% end %></td>
        <td><% if @rp %><%= "#{@rp.rate}%" %><% end %></td>
        <% if exam.status == 0 %>
            <td><%="未开始" %></td>
            <td><%= link_to '查看', student_exam_path(@student, exam) %></td>
            <td><%= link_to '删除', student_exam_path(@student, exam), confirm: 'Are you sure?', method: :delete %></td>
        <% elsif exam.status == 1%>
            <td><%= "正在进行" %></td>
            <td><%= link_to '查看', student_exam_path(@student, exam) %></td>
        <% elsif exam.status == 2%>
            <td><%= "已结束" %></td>
            <td><%= link_to '查看', student_exam_path(@student, exam) %></td>
        <% elsif exam.status == 3%>
            <td><%= "已批改" %></td>
            <td><%= link_to '查看', "/students/#{@student.id}/result_papers/#{@rp.id}/result_words" %></td>
        <% elsif exam.status == 4%>
            <td><%= "未参加" %></td>
            <td><%= link_to '查看', student_exam_path(@student, exam) %></td>
        <% else %>
            <td><%= "状态错误" %></td>
        <% end  %>
    </tr>
    <% end %>
</table>
<%=h will_paginate @exams, :previous_label => '上一页',  :next_label => '下一页'%>

app/views/exams/never_done_exam.html.erb
<h1>未参加的考试</h1>

<%= link_to "Back", student_student_exams_path(current_user)%>
<table>
<% @never_done_exams.each do |p| %>
    <tr>
        <td><%= p.paper.name %></td>
        <td><%= p.start_time.strftime("%Y-%m-%d %H:%M") %></td>
    </tr>
<% end %>
</table>
<%=h will_paginate @never_done_exams, :previous_label => '上一页',  :next_label => '下一页'%>

app/views/exams/new.html.erb
<h1>创建新考试</h1>
<script type="text/javascript">
    $(function() {
            $( "#datepicker_1" ).datetimepicker();
            $( "#datepicker_1" ).datetimepicker( "option", "dateFormat", "yy-mm-dd" );
            $("form").submit(function(e){
               if($( "#datepicker_1" ).val() == ""){
                  alert("请选择考试开始时间!");
                  $( "#datepicker_1" ).focus();
                  return false;
               }
            });
    });
</script>
<%= form_for([@student, @exam], :url => student_exams_path(@student)) do |f| %>

  <div class="field">
    <%= f.label :paper_id, '选择试卷' %><br />
    <%= select_tag 'exam[paper_id]', options_for_select(@papers.collect{ |u| [u.name, u.id] }) %>
  </div>

  <div class="field">
    <%= f.label :start_time, '考试开始时间:'%><br />
    <input type="text" id="datepicker_1" name="exam[start_time]" />
  </div>


  <div class="field">
    <%= f.label :set_time, "设定考试时间(min)"%><br />
    <%= f.select(:set_time, [['10', 10],['15', 15],['20', 20],['25', 25],['30', 30]])  %>
  </div>

  <div class="actions">
    <%= f.submit('Submit') %>
  </div>
<% end %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', student_exams_path(@student) %>
<script type="text/javascript">
	$(function(){
	    $("div.holder").jPages({
	        containerID : "itemContainer"
	    });
	});
</script>

<div>试卷名称:<%= @exam.paper.name %></div>
<div>考试时间:<%= @exam.set_time %>分钟</div>
<div>开始时间:<%= @exam.start_time.strftime("%Y:%H:%M")  %></div>
<div>结束时间:<%= @exam.finish_time.strftime("%Y:%H:%M") %></div>


<div class="holder"></div>
<!-- display the paper -->
<% i=1 %>
<div id="itemContainer">
<% @words.each do |word| %>
    <div> <%= i %> : <%= word.content  %>
          <% word.meanings.each do |ms| %>
              <%= ms.content %>
          <% end %>
    </div>
    <% i = i+1 %>
<% end %>
</div>
<div class="holder"></div>

app/views/exams/show_all.html.erb
<h1>考试列表</h1>

<table>
    <tr>
        <th>试卷名称</th>
        <th>时间(min)</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <% @exams.each do |exam| %>
    <% @rp = ResultPaper.find_by_exam_id(exam.id) %>
    <tr class="change_color">
        <td><%= exam.paper.name %></td>
        <td><%= exam.start_time.strftime("%Y-%m-%d %H:%M") %></td>     
        <td><%= link_to '删除', student_exam_path(@student, exam), confirm: 'Are you sure?', method: :delete %></td>
    </tr>
    <% end %>
</table>
<%=h will_paginate @exams, :previous_label => '上一页',  :next_label => '下一页'%>

app/views/exams/student.html.erb
<h1 style="color:black;">考试类别列表</h1>

<h3><%= link_to "正在进行的考试", doing_exam_student_exams_path(current_user)%></h3>
<h3><%= link_to "未开始的考试", todo_exam_student_exams_path(current_user)%></h3>
<h3><%= link_to "已经答完的考试", done_exam_student_exams_path(current_user)%></h3>
<h3><%= link_to "已经批改的考试", corrected_exam_student_exams_path(current_user)%></h3>
<h3><%= link_to "未参加的考试", never_done_exam_student_exams_path(current_user)%></h3>

app/views/exams/todo_exam.html.erb
<h1>未开始的考试</h1>
<%= link_to "Back", student_student_exams_path(current_user)%>
<table>
<% @todo_exams.each do |p| %>
    <tr>
        <td><%= p.paper.name %></td>
        <td><%= p.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td></td>
    </tr>
<% end %>
</table>
<%=h will_paginate @todo_exams, :previous_label => '上一页',  :next_label => '下一页'%>